create table beef (
beef_id serial primary key,
invoice_date date,
customer varchar(150),
phone varchar(10),
baskets integer,
rows varchar(10),
slaughter integer,
price_slaughter integer,
total_slaughter integer,
qty_cut integer,
price_cut integer,
total_cut integer,
qty_patties integer,
price_patties integer,
total_patties integer,
qty_brand integer,
price_brand integer,
total_brand integer,
qty_other integer,
desc_other varchar(150),
price_other integer,
total_other integer,
total integer,
message text,
address text
)